<?php
$data =[
    [   "name" => "Dwójka",
        "strength" => "2",
        "color" => "Pik",
        "img" => "img/2_of_spades.png",
    ],
    [   "name" => "Trójka",
        "strength" => "3",
        "color" => "Pik",
        "img" => "img/3_of_spades.png",
    ],
    [   "name" => "Czwórka",
        "strength" => "4",
        "color" => "Pik",
        "img" => "img/4_of_spades.png",
    ],
    [   "name" => "Piątka",
        "strength" => "5",
        "color" => "Pik",
        "img" => "img/5_of_spades.png",
    ],
    [   "name" => "Szóstka",
        "strength" => "6",
        "color" => "Pik",
        "img" => "img/6_of_spades.png",
    ],
    [   "name" => "Siódemka",
        "strength" => "7",
        "color" => "Pik",
        "img" => "img/7_of_spades.png",
    ],
    [   "name" => "Ósemka",
        "strength" => "8",
        "color" => "Pik",
        "img" => "img/8_of_spades.png",
    ],
    [   "name" => "Dziewiątka",
        "strength" => "9",
        "color" => "Pik",
        "img" => "img/9_of_spades.png",
    ],
    [   "name" => "Dziesiątka",
        "strength" => "10",
        "color" => "Pik",
        "img" => "img/10_of_spades.png",
    ],
    [   "name" => "Walet",
        "strength" => "11",
        "color" => "Pik",
        "img" => "img/jack_of_spades2.png",
    ],
    [   "name" => "Dama",
        "strength" => "12",
        "color" => "Pik",
        "img" => "img/queen_of_spades2.png",
    ],
    [   "name" => "Król",
        "strength" => "13",
        "color" => "Pik",
        "img" => "img/king_of_spades2.png",
    ],
    [   "name" => "As",
        "strength" => "14",
        "color" => "Pik",
        "img" => "img/ace_of_spades2.png",
    ],

];
