<?php
$data =[
    [   "name" => "Dwójka",
        "strength" => "2",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Trójka",
        "strength" => "3",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Czwórka",
        "strength" => "4",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Piątka",
        "strength" => "5",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Szóstka",
        "strength" => "6",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Siódemka",
        "strength" => "7",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Ósemka",
        "strength" => "8",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Dziewiątka",
        "strength" => "9",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Dziesiątka",
        "strength" => "10",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Walet",
        "strength" => "11",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Dama",
        "strength" => "12",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "Król",
        "strength" => "13",
        "color" => "Pik",
        "img" => "",
    ],
    [   "name" => "As",
        "strength" => "14",
        "color" => "Pik",
        "img" => "",
    ],
    
];
